### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'http_versions'

### ISSUE THREAD

**Issue by CalebJohn** [foxmask/yeoboseyo#10]
I ran into this error while trying to pull feeds.
I'm on httpx version 0.10.1
I checked [the api](https://www.encode.io/httpx/api/#asyncclient) and it seems that http_versions is no longer an option.
removing the http_versions argument seems to fix things for me.

```
❯ python run.py -a go
여보세요 ! RUN and GO
2020-01-04 19:10:47,561 - yeoboseyo.go - INFO - Trigger Marginal Revolution
Traceback (most recent call last):
  File "run.py", line 65, in <module>
    loop.run_until_complete(go())
  File "/home/caleb/anaconda3/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/caleb/programming/apps/yeoboseyo/yeoboseyo/go.py", line 104, in go
    feeds = await rss.get_data(**{'url_to_parse': trigger.rss_url, 'bypass_bozo': config('BYPASS_BOZO')})
  File "/home/caleb/programming/apps/yeoboseyo/yeoboseyo/services/service_rss.py", line 36, in get_data
    async with httpx.AsyncClient(http_versions=["HTTP/1.1"]) as client:
TypeError: __init__() got an unexpected keyword argument 'http_versions'
```

For reference, I'm on Ubuntu 18.04 with python v3.7.3

**Comment by foxmask** [comment]
thanks for reporting
